In [14]:
import pandas as pd
import numpy as np

In [15]:
df = pd.read_csv('convertcsv.csv')

In [16]:
df.head()

req/baseUrl req/body/note/title  \
0   /crm/note        Tina Johnson   
1   /crm/note      Clayton Cooper   
2   /crm/note        Curtis Wolfe   
3   /crm/note        Laura Fisher   
4   /crm/note        Tyler Santos   

                                  req/body/note/desc  req/fresh  \
0  Top recognize eat. Fact whom spend area thing ...      False   
1  As possible American many prepare four strong....      False   
2                Tuesday Notes or 2 like 2 XSP Class      False   
3  State third represent energy campaign not forg...      False   
4  Us enjoy since. Time identify image position o...      False   

  req/headers/host req/headers/user-agent req/headers/content-type  \
0      example.com      insomnia/2020.4.2         application/json   
1      example.com      insomnia/2020.4.2         application/json   
2      example.com      insomnia/2020.4.2         application/json   
3      example.com      insomnia/2020.4.2         application/json   
4      example.com      insomnia/2020.4.2         application/json   

         req/headers/org_id req/headers/user_session_id req/headers/accept  \
0  5f572820f65af8ac955b2e83    5fb27d3750b11901a35649fe                */*   
1  5f572820f65af8ac955b2e83    5fb27d3750b11901a35649fe                */*   
2  5f572820f65af8ac955b2e83    5fb27d3750b11901a35649fe                */*   
3  5f572820f65af8ac955b2e83    5fb27d3750b11901a35649fe                */*   
4  5f572820f65af8ac955b2e83    5fb27d3750b11901a35649fe                */*   

   ...  req/hostname                req/ip req/originalUrl req/path  \
0  ...   example.com  ::ffff:117.99.96.244       /crm/note    /note   
1  ...   example.com  ::ffff:117.99.96.244       /crm/note    /note   
2  ...   example.com  ::ffff:117.99.96.244       /crm/note    /note   
3  ...   example.com  ::ffff:117.99.96.244       /crm/note    /note   
4  ...   example.com  ::ffff:117.99.96.244       /crm/note    /note   

  req/protocol req/secure req/stale req/subdomains/0  req/xhr  isSafe  
0         http      False      True              crm    False    True  
1         http      False      True              crm    False    True  
2         http      False      True              crm    False   False  
3         http      False      True              crm    False    True  
4         http      False      True              crm    False   False  

[5 rows x 23 columns]

In [17]:
df.nunique()

req/baseUrl                      1
req/body/note/title            994
req/body/note/desc             750
req/fresh                        1
req/headers/host                 1
req/headers/user-agent           1
req/headers/content-type         1
req/headers/org_id               1
req/headers/user_session_id      1
req/headers/accept               1
req/headers/content-length       1
req/headers/user/name            1
req/headers/user/role            1
req/hostname                     1
req/ip                           1
req/originalUrl                  1
req/path                         1
req/protocol                     1
req/secure                       1
req/stale                        1
req/subdomains/0                 1
req/xhr                          1
isSafe                           2
dtype: int64

In [18]:
df.isna().sum()

req/baseUrl                    0
req/body/note/title            0
req/body/note/desc             0
req/fresh                      0
req/headers/host               0
req/headers/user-agent         0
req/headers/content-type       0
req/headers/org_id             0
req/headers/user_session_id    0
req/headers/accept             0
req/headers/content-length     0
req/headers/user/name          0
req/headers/user/role          0
req/hostname                   0
req/ip                         0
req/originalUrl                0
req/path                       0
req/protocol                   0
req/secure                     0
req/stale                      0
req/subdomains/0               0
req/xhr                        0
isSafe                         0
dtype: int64

In [19]:
len(df)

1000

In [20]:
df = df[df.columns[[2,-1]]]

In [21]:
df.head()

req/body/note/desc  isSafe
0  Top recognize eat. Fact whom spend area thing ...    True
1  As possible American many prepare four strong....    True
2                Tuesday Notes or 2 like 2 XSP Class   False
3  State third represent energy campaign not forg...    True
4  Us enjoy since. Time identify image position o...   False

In [22]:
df.isSafe.value_counts()

True     572
False    428
Name: isSafe, dtype: int64

In [23]:
df

req/body/note/desc  isSafe
0    Top recognize eat. Fact whom spend area thing ...    True
1    As possible American many prepare four strong....    True
2                  Tuesday Notes or 2 like 2 XSP Class   False
3    State third represent energy campaign not forg...    True
4    Us enjoy since. Time identify image position o...   False
..                                                 ...     ...
995  Recently crime before five thought bit. Card f...    True
996  <img src=1 href=1 onerror="javascript:alert(1)...   False
997  Set nature they then low resource truth. Edge ...    True
998  Push case them such face suffer. Letter middle...    True
999  Family ready stay rule full than yet. Moment o...    True

[1000 rows x 2 columns]

In [24]:
import re
import nltk
from nltk.tokenize import word_tokenize
from nltk.stem import WordNetLemmatizer
from nltk.corpus import stopwords
stwds = stopwords.words('english')
lemma = WordNetLemmatizer()
words = []
corpus = []
def tokenize(text):
    text = re.sub('[^a-zA-Z]',' ',text)
    text = text.lower()
    text = word_tokenize(text)
    text = [lemma.lemmatize(word) for word in text if word not in stwds]
    words.extend(text)
    text = ' '.join(text)
    corpus.append(text)
    return text

In [25]:
df['req/body/note/desc'] = df['req/body/note/desc'].apply(tokenize)

In [26]:
df.isSafe = df.isSafe.apply(lambda x : int(x))
df.head()

req/body/note/desc  isSafe
0  top recognize eat fact spend area thing materi...       1
1  possible american many prepare four strong vis...       1
2                        tuesday note like xsp class       0
3  state third represent energy campaign forget e...       1
4  u enjoy since time identify image position ok ...       0

In [28]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer()
X = cv.fit_transform(df['req/body/note/desc']).toarray()
X

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 1, 0]], dtype=int64)

In [29]:
y = df.isSafe
y

0      1
1      1
2      0
3      1
4      0
      ..
995    1
996    0
997    1
998    1
999    1
Name: isSafe, Length: 1000, dtype: int64

In [30]:
from sklearn.model_selection import cross_val_predict, train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=.25, random_state=101)

In [38]:
from sklearn.naive_bayes import GaussianNB
model_ = GaussianNB()
model_.fit(X_train, y_train)
pred = model_.predict(X_test)

from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
print(accuracy_score(y_test, pred))
print(confusion_matrix(y_test, pred))
print(classification_report(y_test, pred))

0.84
[[ 75  33]
 [  7 135]]
              precision    recall  f1-score   support

           0       0.91      0.69      0.79       108
           1       0.80      0.95      0.87       142

    accuracy                           0.84       250
   macro avg       0.86      0.82      0.83       250
weighted avg       0.85      0.84      0.84       250



In [38]:
from sklearn.naive_bayes import GaussianNB
model_ = GaussianNB()
model_.fit(X_train, y_train)
pred = model_.predict(X_test)

from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
print(accuracy_score(y_test, pred))
print(confusion_matrix(y_test, pred))
print(classification_report(y_test, pred))

0.84
[[ 75  33]
 [  7 135]]
              precision    recall  f1-score   support

           0       0.91      0.69      0.79       108
           1       0.80      0.95      0.87       142

    accuracy                           0.84       250
   macro avg       0.86      0.82      0.83       250
weighted avg       0.85      0.84      0.84       250



In [39]:
from sklearn.svm import SVC
model = SVC(kernel='rbf')
model.fit(X_train, y_train)
pred = model.predict(X_test)

from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
print(accuracy_score(y_test, pred))
print(confusion_matrix(y_test, pred))
print(classification_report(y_test, pred))

0.848
[[ 70  38]
 [  0 142]]
              precision    recall  f1-score   support

           0       1.00      0.65      0.79       108
           1       0.79      1.00      0.88       142

    accuracy                           0.85       250
   macro avg       0.89      0.82      0.83       250
weighted avg       0.88      0.85      0.84       250



## For predictions, give only 'req/body/note/desc' column

In [82]:
def predictor(df):
    result = []
    for desc in df['req/body/note/desc']:
        text = tokenize(desc)
        text = cv.transform([text]).toarray()
        result.append(bool(model.predict(text)[0]))
    return result

In [83]:
predictor(df)

[True,
 True,
 False,
 True,
 False,
 False,
 True,
 False,
 False,
 False,
 False,
 False,
 True,
 True,
 False,
 True,
 False,
 True,
 True,
 False,
 False,
 False,
 True,
 False,
 False,
 False,
 True,
 False,
 True,
 False,
 False,
 True,
 True,
 True,
 True,
 False,
 True,
 True,
 True,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 True,
 True,
 False,
 False,
 False,
 True,
 True,
 True,
 True,
 True,
 False,
 False,
 True,
 True,
 False,
 True,
 False,
 False,
 True,
 True,
 False,
 True,
 True,
 False,
 True,
 True,
 True,
 False,
 False,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 True,
 False,
 False,
 True,
 True,
 False,
 False,
 True,
 True,
 True,
 True,
 False,
 True,
 False,
 False,
 True,
 False,
 True,
 False,
 False,
 False,
 True,
 False,
 False,
 True,
 True,
 False,
 True,
 True,
 True,
 False,
 True,
 False,
 True,
 True,
 True,
 False,
 False,
 True,
 True,
 True,
 True,
 True,
 False,
 True,
 True,
 True,
 False,
 False,
 True,
 True